version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    labels:
      - "chore"

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
